version: "3.9"
services:
  web:
    container_name: daruma
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "crond && rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    restart: on-failure
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL_SIDEKIQ: ${REDIS_URL_SIDEKIQ}

  db:
    image: postgres:alpine3.18
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    restart: on-failure

  redis:
    image: redis:alpine3.18
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
    restart: on-failure

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bundle exec sidekiq
    volumes:
      - './web:/app'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL_SIDEKIQ: ${REDIS_URL_SIDEKIQ}
    restart: on-failure
