default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: daruma
  host: db
  username: <%= Rails.application.credentials.dig(:db_user) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>

